### PR TITLE
fix: address PR feedback

### LINKED ISSUE #38: Quests follow-up
Follow-up issue to address feedback on https://github.com/penumbra-zone/guide/pull/30

### PR DESCRIPTION
**Pull request by vacekj**
fixes #38 by addressing feedback from #30

### CODE REVIEW

File: components/Deposit.tsx [hunk 1]
```diff
@@ -37,7 +37,7 @@ const Deposit: React.FC = () => {
     ) ?? [];
 
   const { scanSinceBlockHeight } = useQuestStore();
-  console.log(showOld);
+  showOld;
```
Comment (grod220) [inline components/Deposit.tsx:40]: nit: remove

File: components/Deposit.tsx [hunk 2]
```diff
@@ -49,7 +49,7 @@ const Deposit: React.FC = () => {
     staleTime: 0,
     initialData: [],
     queryFn: async () => {
-      console.log('refetch');
+      ('refetch');
```
Comment (grod220) [inline components/Deposit.tsx:52]: nit: remove

File: components/Staking.tsx [hunk 3]
```diff
@@ -38,19 +38,17 @@ const Staking: React.FC = () => {
...
+          .metadata!.symbol = truncateMiddle(
+          (bal.balanceView?.valueView?.value as ValueView_KnownAssetId)!
+            .metadata!.symbol,
           30,
         );
         return bal;
       }) ?? [];
 
-  console.log(delegationTokens.length, balances?.length, balances);
+  delegationTokens.length, balances?.length, balances;
```
Comment (grod220) [inline components/Staking.tsx:51]: nit: remove

File: components/hooks.ts [hunk 4]
```diff
@@ -241,7 +241,7 @@ export function useSwaps(blockRange: BlockRange) {
             action.action?.case === 'swapClaim',
         ),
       );
-      console.log(swaps);
+      swaps;
```
Comment (grod220) [inline components/hooks.ts:244]: nit: remove

File: components/Staking.tsx [hunk 5]
```diff
@@ -38,19 +38,17 @@ const Staking: React.FC = () => {
...
-        // @ts-expect-error bufs for the win
-        (
-          bal.balanceView?.valueView?.value as ValueView_KnownAssetId
-        ).metadata.symbol = truncateMiddle(
-          // @ts-expect-error bufs for the win
-          (bal.balanceView?.valueView?.value as ValueView_KnownAssetId).metadata
-            .symbol,
+
+        (bal.balanceView?.valueView?.value as ValueView_KnownAssetId)!
+          .metadata!.symbol = truncateMiddle(
```
Comment (grod220) [inline components/Staking.tsx:43]: question: did you check if there was a getter in `/web` for getting symbols? If so you should use that.

File: components/Balances.tsx [hunk 6]
```diff
@@ -7,14 +7,9 @@ export function Balances() {
...
-    ? balances
-        .map((bal) => bal.balanceView)
-        .map((balanceView) => (
-          <BalanceRow
-            key={balanceView!.toJsonString()}
-            balance={balanceView!}
-          />
-        ))
+    ? balances.map(({ balanceView }) => (
+        <BalanceRow key={balanceView!.toJsonString()} balance={balanceView!} />
```
Comment (grod220) [inline components/Balances.tsx:11]: suggestion: generally it's better to just use a conditional instead of a `!`. Because if something goes wrong, you'll get a readable error versus something like `could not find toJsonString of undefined`. It would look something like:

```ts
if (!balanceView) throw new Error("No balance view on balance data")
```

**Review by grod220 — APPROVED** [review]
A few comments, but feel free to merge after

File: components/Staking.tsx (hunk 5 above)
Comment (vacekj) [reply components/Staking.tsx:43]: The symbol truncation here is for cosmetic reasons. I did not find anything like this in the web repo upon a brief look, happy to be proven wrong tho.

File: components/Balances.tsx (hunk 6 above)
Comment (vacekj) [reply components/Balances.tsx:11]: agree, added an additional check: 
```  return balances && balances.every((b) => b.balanceView !== undefined)```

File: components/Staking.tsx (hunk 5 above)
Comment (grod220) [reply components/Staking.tsx:43]: Nah, was thinking something more like this for getting the symbol from the buf type: https://github.com/penumbra-zone/web/blob/074584500b1dd143c927cadb8ceb85d0b72e5204/packages/getters/src/value-view.ts#L68

Comment (vacekj) [reply components/Staking.tsx:43]: Ahhh I see! Thanks for the suggestion, fixed.

**Comment by TalDerei** [comment]
LGTM
